### ISSUE TITLE
Doc: Example how to push reports

### ISSUE THREAD

**Issue by lcmgh** [elegoff/sonar-rust#57]
Just went through the FAQ and doc and could not find an example how to push e.g. an tarpaulin generated code coverage report (from a GitHub actions based build). I'm unfortunately not familar with sonar-scanner and not could not find appropriate options or starting points.

**Comment by lcmgh** [comment]
That was fairly easy.

```yaml
      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v3
        
      - name: Run cargo-tarpaulin
        shell: bash
        run: |
          RUN_MODE=local cargo tarpaulin --ignore-tests --all-features --release --out Lcov
          sonar-scanner -Dcommunity.rust.lcov.reportPaths=lcov.info -Dsonar.login=${{ secrets.SONAR_TOKEN }}
```
